### ISSUE TITLE
USER STORY: Admin manage user accounts

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#12]
As an **admin** I can **manage user accounts** so that **I can maintain the integrity of the platform.**

### Acceptance criteria

- The admin can view a list of users and their accounts.

### Tasks

- [X] Add functionality to view a list of users.
- [X] Implement user account management features.
- [X] Test viewing and managing user accounts.
