### ISSUE TITLE
USER STORY: View Reviews and Ratings

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#14]
As a **user** I can **view reviews and ratings left by other users** so that **I can make an informed decision before renting a car.**

### Acceptance criteria

- The about page displays a list of user reviews and their ratings.

- The average rating (based on all user ratings) is displayed prominently on the car's detail page.

### Tasks

- [X] Display user reviews on the my reviews page.
- [X] Show ratings left by other users.
- [X] Test review and rating display.
