### ISSUE TITLE
USER STORY: Store customer support form in the database

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#15]
As a **Site Owner** I can **store customer support form in the database** so that **I can review them.**

### Acceptance criteria

- Save form in the database

- Review saved form

### Tasks

- [X] Save support form data.
- [X] Create a way to view saved forms.
- [X] Test saving and reviewing forms.
