### ISSUE TITLE
USER STORY: Mark requests as "read"

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#16]
As a **Site Owner** I can **mark user requests as "read"** so that **I can see how many I still need to process.**

### Acceptance criteria

- Mark requests as "read"

### Tasks

- [X] Add functionality to mark requests as "read."
- [X] Update request status in the database.
- [X] Test marking and updating request status.
