### ISSUE TITLE
USER STORY: View the location of each office on a Map

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#17]
As a **user** I can **view the location of each office on a Map** so that **I can easily find and navigate to the office.**

### Acceptance criteria

- Each office detail page displays an embedded Map showing the office location.

- The map is correctly centered and pinned at the office address provided.

### Tasks

- [X] Add a map to the office detail page.
- [X] Center and pin the map at the office location.
- [X] Test the map display.
