### ISSUE TITLE
USER STORY: Add and update the office locations on Maps

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#18]
As a **admin** I can **add and update the office locations on Google** so that **users can see the accurate location of each office.**

### Acceptance criteria

- The admin can enter or update the address of an office, and the changes are reflected on the Map embedded on the office detail page.

- The map updates correctly to show the new or updated location when the office address is changed.

### Tasks

- [X] Add/update office addresses.
- [X] Update map with new addresses.
- [X] Test map updates.
