### ISSUE TITLE
USER STORY: Reset Password

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#20]
As a **user who has forgotten their password,** I can **be able to reset my password,** so that **I can regain access to my account.**

### Acceptance criteria

- Password Recovery Request
Given a user is on the login page, when they click on the "Forgot Password?" link, then they should be redirected to a password recovery page where they can enter their email address.

- Given a user has entered a valid email address and submitted the password recovery form, when the request is processed, then the user should receive an email with a password reset link. And the email should include instructions on how to reset their password.
And the user should see a confirmation message on the site indicating that an email has been sent.

- Password Reset Link
Given a user receives a password reset email, when they click on the reset link, then they should be redirected to a page where they can enter and confirm a new password. And the reset link should be valid for a limited time to ensure security.

- New Password Submission
Given a user is on the password reset page, when they enter and confirm their new password, then their password should be updated in the system. And the user should be redirected to the login page with a message confirming that their password has been successfully reset.

### Tasks

- [X] Add "Forgot Password?" link on login page.
- [X] Create password recovery form.
- [X] Send password reset email with instructions.
- [X] Create password reset form.
- [X] Update password and redirect to login.
- [X] Test the entire password reset process.
