### ISSUE TITLE
EPIC: Admin and Customer Support

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#25]
Description: This epic encompasses the features related to admin functionalities and customer support operations.

Epic Tasks:
- [x] [USER STORY: Admin Car Management #11](https://github.com/OleksiiKova/rent-car-ireland/issues/11)
- [x] [USER STORY: Admin manage user accounts #12](https://github.com/OleksiiKova/rent-car-ireland/issues/12)
- [x] [USER STORY: Customer Support #10](https://github.com/OleksiiKova/rent-car-ireland/issues/10)
- [x] [USER STORY: Store customer support form in the database #15](https://github.com/OleksiiKova/rent-car-ireland/issues/15)
- [x] [USER STORY: Mark requests as "read" #16](https://github.com/OleksiiKova/rent-car-ireland/issues/16)
