### ISSUE TITLE
USER STORY: Booking Management (view my current and past bookings)

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#8]
As a **registered user** I can **view my current and past bookings** so that **I can keep track of my rental history.**

### Acceptance criteria

- The user can view a list of their current and past bookings.

- Each booking displays key details such as rental dates, car, and booking status.

### Tasks

- [X] Create bookings page with tabs or sections for current and past bookings.
- [X] Fetch and display a list of the user’s active bookings.
- [X] Fetch and display a list of the user’s past bookings.
- [X] Show key details for each booking, including car, booking and customer informations.
- [X] Ensure responsive design for viewing on different devices.
- [X] Test booking history functionality.
