### ISSUE TITLE
USER STORY: Booking Management (cancel an upcoming booking)

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/rent-car-ireland#9]
As a **registered user** I can **cancel an upcoming booking** so that **I can change my plans if necessary.**

### Acceptance criteria

- The user can select an upcoming booking and initiate the cancellation process.

- After canceling, the user receives a confirmation, and the booking status updates to "canceled".

### Tasks

- [X] Add delete button.
- [X] Implement delete confirmation dialog.
- [X] Display on-screen delete confirmation.
- [X] Test the delete process.
